# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-11 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_message'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StatusUpdate',
            new_name='ProfileFeedItem',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
